server:
  port: 8888
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 91cfe12f58e3a27f6fd3
            client-secret: 6abcaffa431a2e573e0fbe0cb3b49cc6473aa9f0

